USE cars_stage;

SELECT `data-make`,
    `data-model`,
    `data-year`,
    `data-trim`,
    IFNULL(nullif(`data-extcolor`,''), 'UNK') as `data-extcolor`,
    IFNULL(nullif(`data-intcolor`,''), 'UNK') as `data-intcolor`,
    IFNULL(nullif(`data-trans`,''), 'UNK') as `data-trans`,
    `data-price`,
    `data-engine`,
    `data-fueltype`,
    `data-vehicletype`,
    `data-bodystyle`,
    `data-name`,
    `data-vin`,
    `data-modelcode`,
    `data-stocknum`
FROM `dat_american_cars`
ORDER BY `data-make`,
    `data-model`,
    `data-year`,
    `data-trim`,
    `data-extcolor`,
    `data-intcolor`,
    `data-trans`,
    `data-price`,
    `data-engine`,
    `data-fueltype`,
    `data-vehicletype`,
    `data-bodystyle`,
    `data-name`,
    `data-vin`,
    `data-modelcode`,
    `data-stocknum`